package net.runelite.client.plugins.NQuickFighter;

public enum NQuickFighterState
{
	ANIMATING,
	MOVING,
	TIMEOUT,
	DEPOSIT_ITEMS,
	CLIMB_LADDER,
	CLIMB_LADDER2,
	LOOT_ITEMS,
	JUMP_OBSTACLE,
	JUMP_OBSTACLE2,
	BURY_BONES,
	ATTACK,
	WITHDRAW_ITEMS,
	UNHANDLED_STATE;
}
